// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/Test_Bolt_API/pkg/models/shared"
	"net/http"
)

type PaymentsActionRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The ID of the payment to operate on
	ID                   string                      `pathParam:"style=simple,explode=false,name=id"`
	PaymentActionRequest shared.PaymentActionRequest `request:"mediaType=application/json"`
}

func (o *PaymentsActionRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *PaymentsActionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *PaymentsActionRequest) GetPaymentActionRequest() shared.PaymentActionRequest {
	if o == nil {
		return shared.PaymentActionRequest{}
	}
	return o.PaymentActionRequest
}

type PaymentsActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The action was successfully applied to the pending payment
	PaymentResponse interface{}
}

func (o *PaymentsActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PaymentsActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PaymentsActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PaymentsActionResponse) GetPaymentResponse() interface{} {
	if o == nil {
		return nil
	}
	return o.PaymentResponse
}
