// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/Test_Bolt_API/pkg/models/shared"
	"net/http"
)

type TransactionActionSecurity struct {
	APIKey string `security:"scheme,type=apiKey,subtype=header,name=X-API-Key"`
}

func (o *TransactionActionSecurity) GetAPIKey() string {
	if o == nil {
		return ""
	}
	return o.APIKey
}

type TransactionActionRequest struct {
	// The publicly viewable identifier used to identify a merchant division.
	XPublishableKey string `header:"style=simple,explode=false,name=X-Publishable-Key"`
	// The transaction reference
	ID                       string                          `pathParam:"style=simple,explode=false,name=id"`
	TransactionActionRequest shared.TransactionActionRequest `request:"mediaType=application/json"`
}

func (o *TransactionActionRequest) GetXPublishableKey() string {
	if o == nil {
		return ""
	}
	return o.XPublishableKey
}

func (o *TransactionActionRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *TransactionActionRequest) GetTransactionActionRequest() shared.TransactionActionRequest {
	if o == nil {
		return shared.TransactionActionRequest{}
	}
	return o.TransactionActionRequest
}

type TransactionActionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// The action was successfully applied
	Transaction *shared.Transaction
}

func (o *TransactionActionResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *TransactionActionResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *TransactionActionResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *TransactionActionResponse) GetTransaction() *shared.Transaction {
	if o == nil {
		return nil
	}
	return o.Transaction
}
