// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// DotTag - The type of error returned
type DotTag string

const (
	DotTagInvalidRegion     DotTag = "invalid_region"
	DotTagInvalidPostalCode DotTag = "invalid_postal_code"
)

func (e DotTag) ToPointer() *DotTag {
	return &e
}

func (e *DotTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "invalid_region":
		fallthrough
	case "invalid_postal_code":
		*e = DotTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for DotTag: %v", v)
	}
}

type AddressError struct {
	// The type of error returned
	DotTag DotTag `json:".tag"`
	// A human-readable error message, which might include information specific to
	// the request that was made.
	//
	Message string `json:"message"`
}

func (o *AddressError) GetDotTag() DotTag {
	if o == nil {
		return DotTag("")
	}
	return o.DotTag
}

func (o *AddressError) GetMessage() string {
	if o == nil {
		return ""
	}
	return o.Message
}
