// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type Action string

const (
	ActionRedirect Action = "redirect"
)

func (e Action) ToPointer() *Action {
	return &e
}

func (e *Action) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "redirect":
		*e = Action(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Action: %v", v)
	}
}

type SchemasStatus string

const (
	SchemasStatusAwaitingUserConfirmation SchemasStatus = "awaiting_user_confirmation"
)

func (e SchemasStatus) ToPointer() *SchemasStatus {
	return &e
}

func (e *SchemasStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "awaiting_user_confirmation":
		*e = SchemasStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for SchemasStatus: %v", v)
	}
}

type PaymentResponsePendingSchemas struct {
	Action Action        `json:"action"`
	ID     *string       `json:"id,omitempty"`
	Status SchemasStatus `json:"status"`
	URL    string        `json:"url"`
}

func (o *PaymentResponsePendingSchemas) GetAction() Action {
	if o == nil {
		return Action("")
	}
	return o.Action
}

func (o *PaymentResponsePendingSchemas) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PaymentResponsePendingSchemas) GetStatus() SchemasStatus {
	if o == nil {
		return SchemasStatus("")
	}
	return o.Status
}

func (o *PaymentResponsePendingSchemas) GetURL() string {
	if o == nil {
		return ""
	}
	return o.URL
}

type Status string

const (
	StatusSuccess Status = "success"
)

func (e Status) ToPointer() *Status {
	return &e
}

func (e *Status) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		*e = Status(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Status: %v", v)
	}
}

type PaymentResponseFinalizedSchemas struct {
	ID          *string     `json:"id,omitempty"`
	Status      Status      `json:"status"`
	Transaction Transaction `json:"transaction"`
}

func (o *PaymentResponseFinalizedSchemas) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PaymentResponseFinalizedSchemas) GetStatus() Status {
	if o == nil {
		return Status("")
	}
	return o.Status
}

func (o *PaymentResponseFinalizedSchemas) GetTransaction() Transaction {
	if o == nil {
		return Transaction{}
	}
	return o.Transaction
}
