// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PaymentMethodCreditCardTag string

const (
	PaymentMethodCreditCardTagCreditCard PaymentMethodCreditCardTag = "credit_card"
)

func (e PaymentMethodCreditCardTag) ToPointer() *PaymentMethodCreditCardTag {
	return &e
}

func (e *PaymentMethodCreditCardTag) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "credit_card":
		*e = PaymentMethodCreditCardTag(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PaymentMethodCreditCardTag: %v", v)
	}
}

// Network - The credit card's network.
type Network string

const (
	NetworkVisa         Network = "visa"
	NetworkMastercard   Network = "mastercard"
	NetworkAmex         Network = "amex"
	NetworkDiscover     Network = "discover"
	NetworkJcb          Network = "jcb"
	NetworkUnionpay     Network = "unionpay"
	NetworkAlliancedata Network = "alliancedata"
	NetworkCitiplcc     Network = "citiplcc"
)

func (e Network) ToPointer() *Network {
	return &e
}

func (e *Network) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "visa":
		fallthrough
	case "mastercard":
		fallthrough
	case "amex":
		fallthrough
	case "discover":
		fallthrough
	case "jcb":
		fallthrough
	case "unionpay":
		fallthrough
	case "alliancedata":
		fallthrough
	case "citiplcc":
		*e = Network(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Network: %v", v)
	}
}

type PaymentMethodCreditCardOutput struct {
	DotTag PaymentMethodCreditCardTag `json:".tag"`
	// The ID of credit card's billing address.
	BillingAddressID *string `json:"billing_address_id,omitempty"`
	// The expiration date, in YYYY-MM format.
	Expiration string  `json:"expiration"`
	ID         *string `json:"id,omitempty"`
	// The account number's last four digits.
	Last4 string `json:"last4"`
	// The credit card's network.
	Network Network `json:"network"`
}

func (o *PaymentMethodCreditCardOutput) GetDotTag() PaymentMethodCreditCardTag {
	if o == nil {
		return PaymentMethodCreditCardTag("")
	}
	return o.DotTag
}

func (o *PaymentMethodCreditCardOutput) GetBillingAddressID() *string {
	if o == nil {
		return nil
	}
	return o.BillingAddressID
}

func (o *PaymentMethodCreditCardOutput) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *PaymentMethodCreditCardOutput) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PaymentMethodCreditCardOutput) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCreditCardOutput) GetNetwork() Network {
	if o == nil {
		return Network("")
	}
	return o.Network
}

type PaymentMethodCreditCard struct {
	DotTag         PaymentMethodCreditCardTag `json:".tag"`
	BillingAddress AddressReference           `json:"billing_address"`
	// The Bank Identification Number (BIN). This is typically the first 4 to 6 digits of the account number.
	Bin string `json:"bin"`
	// The expiration date, in YYYY-MM format.
	Expiration string `json:"expiration"`
	// The account number's last four digits.
	Last4 string `json:"last4"`
	// The credit card's network.
	Network Network `json:"network"`
	// The Bolt token associated with the credit card.
	Token string `json:"token"`
}

func (o *PaymentMethodCreditCard) GetDotTag() PaymentMethodCreditCardTag {
	if o == nil {
		return PaymentMethodCreditCardTag("")
	}
	return o.DotTag
}

func (o *PaymentMethodCreditCard) GetBillingAddress() AddressReference {
	if o == nil {
		return AddressReference{}
	}
	return o.BillingAddress
}

func (o *PaymentMethodCreditCard) GetBillingAddressExplicit() *SchemasInput {
	return o.GetBillingAddress().SchemasInput
}

func (o *PaymentMethodCreditCard) GetBillingAddressID() *Schemas {
	return o.GetBillingAddress().Schemas
}

func (o *PaymentMethodCreditCard) GetBin() string {
	if o == nil {
		return ""
	}
	return o.Bin
}

func (o *PaymentMethodCreditCard) GetExpiration() string {
	if o == nil {
		return ""
	}
	return o.Expiration
}

func (o *PaymentMethodCreditCard) GetLast4() string {
	if o == nil {
		return ""
	}
	return o.Last4
}

func (o *PaymentMethodCreditCard) GetNetwork() Network {
	if o == nil {
		return Network("")
	}
	return o.Network
}

func (o *PaymentMethodCreditCard) GetToken() string {
	if o == nil {
		return ""
	}
	return o.Token
}
