// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TransactionUpdateRequestCart struct {
	// A shopper-facing identifier corresponding to the order reference associated with this transaction.
	DisplayID *string `json:"display_id,omitempty"`
}

func (o *TransactionUpdateRequestCart) GetDisplayID() *string {
	if o == nil {
		return nil
	}
	return o.DisplayID
}

type Order struct {
	Cart *TransactionUpdateRequestCart `json:"cart,omitempty"`
}

func (o *Order) GetCart() *TransactionUpdateRequestCart {
	if o == nil {
		return nil
	}
	return o.Cart
}

type TransactionUpdateRequest struct {
	Order *Order `json:"order,omitempty"`
}

func (o *TransactionUpdateRequest) GetOrder() *Order {
	if o == nil {
		return nil
	}
	return o.Order
}
