// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"errors"
	"fmt"
	"github.com/speakeasy-sdks/Test_Bolt_API/pkg/utils"
)

type ActionType string

const (
	ActionTypeCapture ActionType = "capture"
	ActionTypeRefund  ActionType = "refund"
	ActionTypeVoid    ActionType = "void"
)

type Action struct {
	TransactionActionCapture *TransactionActionCapture
	TransactionActionRefund  *TransactionActionRefund
	TransactionActionVoid    *TransactionActionVoid

	Type ActionType
}

func CreateActionCapture(capture TransactionActionCapture) Action {
	typ := ActionTypeCapture
	typStr := TransactionActionCaptureTag(typ)
	capture.DotTag = typStr

	return Action{
		TransactionActionCapture: &capture,
		Type:                     typ,
	}
}

func CreateActionRefund(refund TransactionActionRefund) Action {
	typ := ActionTypeRefund
	typStr := TransactionActionRefundTag(typ)
	refund.DotTag = typStr

	return Action{
		TransactionActionRefund: &refund,
		Type:                    typ,
	}
}

func CreateActionVoid(void TransactionActionVoid) Action {
	typ := ActionTypeVoid
	typStr := TransactionActionVoidTag(typ)
	void.DotTag = typStr

	return Action{
		TransactionActionVoid: &void,
		Type:                  typ,
	}
}

func (u *Action) UnmarshalJSON(data []byte) error {

	type discriminator struct {
		DotTag string
	}

	dis := new(discriminator)
	if err := json.Unmarshal(data, &dis); err != nil {
		return fmt.Errorf("could not unmarshal discriminator: %w", err)
	}

	switch dis.DotTag {
	case "capture":
		transactionActionCapture := new(TransactionActionCapture)
		if err := utils.UnmarshalJSON(data, &transactionActionCapture, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.TransactionActionCapture = transactionActionCapture
		u.Type = ActionTypeCapture
		return nil
	case "refund":
		transactionActionRefund := new(TransactionActionRefund)
		if err := utils.UnmarshalJSON(data, &transactionActionRefund, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.TransactionActionRefund = transactionActionRefund
		u.Type = ActionTypeRefund
		return nil
	case "void":
		transactionActionVoid := new(TransactionActionVoid)
		if err := utils.UnmarshalJSON(data, &transactionActionVoid, "", true, true); err != nil {
			return fmt.Errorf("could not unmarshal expected type: %w", err)
		}

		u.TransactionActionVoid = transactionActionVoid
		u.Type = ActionTypeVoid
		return nil
	}

	return errors.New("could not unmarshal into supported union types")
}

func (u Action) MarshalJSON() ([]byte, error) {
	if u.TransactionActionCapture != nil {
		return utils.MarshalJSON(u.TransactionActionCapture, "", true)
	}

	if u.TransactionActionRefund != nil {
		return utils.MarshalJSON(u.TransactionActionRefund, "", true)
	}

	if u.TransactionActionVoid != nil {
		return utils.MarshalJSON(u.TransactionActionVoid, "", true)
	}

	return nil, errors.New("could not marshal union type: all fields are null")
}

type TransactionActionRequest struct {
	Action Action `json:"action"`
}

func (o *TransactionActionRequest) GetAction() Action {
	if o == nil {
		return Action{}
	}
	return o.Action
}

func (o *TransactionActionRequest) GetActionCapture() *TransactionActionCapture {
	return o.GetAction().TransactionActionCapture
}

func (o *TransactionActionRequest) GetActionRefund() *TransactionActionRefund {
	return o.GetAction().TransactionActionRefund
}

func (o *TransactionActionRequest) GetActionVoid() *TransactionActionVoid {
	return o.GetAction().TransactionActionVoid
}
